### ISSUE TITLE
Monotonically ordered coordinates vs. CRS

### ISSUE THREAD

**Issue by neothemachine** [Reading-eScience-Centre/coveragejson#10]
As in netCDF-CF we want coordinate arrays (e.g. `"x"` or `"t"`) to be monotonically ordered, sometimes even monotonically increasing in case of times for trajectories or point series.

The question is how does that work in theory for arbitrary CRS's? Does a CRS define an order relation for each axis? Is that even possible for longitudes? I know that practically you just look at the numbers and say that when crossing the date line you just go further and exceed the strict [-180,180] extent. But it would be nice to have some formal theory behind that. The same for times and arbitrary calendars, time standards, string formats...

**Comment by neothemachine** [comment]
Is there some expert we can ask for advice here?

Currently the spec has for domain axis values:
> The value of "values" is a non-empty array of axis values. The values in that array must be ordered monotonically according to their ordering relation defined by the used referencing system.

Apart from the spatial CRS issues around longitude this phrasing breaks for composite axes, and also for reference systems which don't have an ordering relation. So I think for the first release we have to fix that somehow.

**Comment by jonblower** [comment]
I think here we just have to adjust the words so that it's clear that they only refer to numeric, "simple" axes. (Specific domain types might make further restrictions for composite axes: e.g. trajectories would want their axis ordered in time.)

**Comment by neothemachine** [comment]
Changing it to refer to numeric axes only is simple, but what about string-type temporal axes (non-composite)? Surely the same restriction should apply as well here. Should that be special cases and explicitly mention temporal reference systems?

**Comment by jonblower** [comment]
It's really a common-sense rule. Maybe we can just say "if there is a natural ordering to axis values, use it monotonically". Time axes should normally be in ascending order, but there are cases where it makes more sense to look into the past (e.g. when you're interested in how long ago something happened).

**Comment by neothemachine** [comment]
Ok, I rewrote it and restricted it to primitive axis values. Still, I file this under "good enough" and slightly underspecified, especially when looking at longitudes, and also since we don't really define what "natural ordering" really means, but as you said, common-sense should work here.

"- If `"dataType"` is `"Primitive"` and the associated reference system (see 6.1.2) defines a natural ordering of values then the array values must be ordered monotonically, that is, increasing or decreasing."
