### ISSUE TITLE
Domain as URL

### ISSUE THREAD

**Issue by neothemachine** [Reading-eScience-Centre/coveragejson#11]
When having a range as URL in a RangeSet you still know to which parameter it belongs because it is a map from parameter id to range. For the domain, this is not the case and you would not know the type of the domain without loading it. This is relevant mostly for coverage collections where you might want to lazy load the actual domain and ranges (should you have a server API that allows such organisation) but still want to display some limited metadata about the coverage including its domain type.

The question is: Can we fix that and how?

**Comment by jonblower** [comment]
You could either:
 (1) Include the type with the domain URL in an object, or
 (2) Give the Coverages more precise names (e.g. PointSeriesCoverage). Then the client knows what kind of domain to expect.

I'm in favour of (2), which also follows practice in CSML etc (although not GeoJSON, as you have pointed out).

**Comment by neothemachine** [comment]
Hm not sure about (2), that would mean there is an explosion of CoverageJSON document types: "Grid", "Profile", "PointSeries", "Point", "Trajectory", "Section", "MultiPolygonSeries", "MultiPolygon", "Polygon", "GridCoverage", "ProfileCoverage", "PointSeriesCoverage", "PointCoverage", "TrajectoryCoverage", "SectionCoverage", "MultiPolygonSeriesCoverage", "MultiPolygonCoverage", "PolygonCoverage", "Range", "Coverage", or "CoverageCollection"..... where the domain ones would probably have to be renamed to *Domain.

What about adding the domain type as separate field if the domain is not embedded? Like
```js
"domain": "URL",
"domainType": "Grid"
```
Not sure if I like that either.

**Comment by jonblower** [comment]
Yes, your suggestion was my suggestion (1). But I still prefer (2) to be honest. It's not an explosion of document types, because they are all still Coverages after all. It's only a label and doesn't affect the spec much IMO.

**Comment by neothemachine** [comment]
What about the CoverageCollection? This should not be prefixed, right?

**Comment by jonblower** [comment]
I'm not sure what you mean by "prefixed". If you mean "we don't need any more precise types for CoverageCollection" then I agree. I don't think we want a PointSeriesCoverageCollection, etc.

**Comment by neothemachine** [comment]
Since I implemented this now (adding the domain to the covergae type like "GridCoverage" etc.) and it seems to work fairly well and given that we have a limited number of coverage types in CoverageJSON, I will incorporate the change in the spec now.
