### ISSUE TITLE
Cannot define two LD types for a term within context

### ISSUE THREAD

**Issue by neothemachine** [Reading-eScience-Centre/coveragejson#13]
I wanted to do the following to make a coverage both a Coverage and an O&M Observation without having an array for the type value:
```js

{
  "@context": {
    "Coverage": ["covjson:Coverage", "oml:Observation"]
  },
  "type": "Coverage"
}
```
But turns out this is not allowed unfortunately. I will remove the O&M for now. The only alternative I see is to not use our covjson term here which would be inconsistent, or have type as `"type": ["Coverage","Observation"]` which is quite inconvenient for clients.

**Comment by jonblower** [comment]
Yes, I think this might just have to be defined externally. Can it be recorded in a document that describes a dataset (e.g. returned from a catalogue)?

**Comment by neothemachine** [comment]
Well, what you want to define is basically:
```js
{
  "@context": [
    "http://.../covjson/basecontext.jsonld",
    { "oml": "http://def.seegrid.csiro.au/ontology/om/om-lite#" }
  ],
  "id": "Coverage",
  "type": "oml:Observation"
}
```
So, within a (DCAT) dataset you would have to use an array as root to have multiple node objects:
```js
[{
  ...DCAT dataset...
},
{
  "@context": [
    "http://.../covjson/basecontext.jsonld",
    { "oml": "http://def.seegrid.csiro.au/ontology/om/om-lite#" }
  ],
  "id": "Coverage",
  "type": "oml:Observation"
}]
```

There may be an alternative but I'm not sure, and that is you can use `@graph`:
```js
{
  "@context": [
    "http://.../covjson/basecontext.jsonld",
    { "oml": "http://def.seegrid.csiro.au/ontology/om/om-lite#" }
  ],
  ...DCAT dataset...,
  "@graph": {
    "id": "Coverage",
    "type": "oml:Observation"
  }
}
```
The result is exactly the same but the JSON-LD spec says that the root resource would then be a named graph, but this information gets lost when converting to RDF triples. So, I'd say this is nicer, but it may have slightly different semantics.

**Comment by neothemachine** [comment]
I will close this for now, I think it's not that important since such relationships can always be defined somewhere else. There will be other classes as well and we will never include all possible ones anyway.
