### ISSUE TITLE
Allow multiple range values to map to the same category

### ISSUE THREAD

**Issue by jonblower** [Reading-eScience-Centre/coveragejson#16]
Usually for a categorical dataset, the range will be encoded as integers, each of which maps to a different category (e.g. forest, surface water, etc). But one of the things we want to do in MELODIES is to allow remapping of a dataset from one set of categories to another (usually smaller and more general) set. This could be done by changing all the values of the range, but a neater way would be simply to change the parameter set and the contained category mapping. For example:

Source data:
```js
"categories": [ {
      "value": 1,
      "label": "Arable farmland"
    },{
      "value": 2,
      "label": "Livestock farmland"
  }, ...
]
```

Remapped data:
```js
"categories": [ {
      "values": [1,2],
      "label": "Farmland"
    }, ...
   ]
```

The implication of this is that we should allow multiple range values to map to the same category. (The overall idea is that this mapping could be done automatically, through ontologies.)

**Comment by neothemachine** [comment]
That makes sense, should be an easy change to the spec.
