### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by neothemachine** [Reading-eScience-Centre/coveragejson#17]
We should not forgot about different languages for the labels and descriptions. The question is if and how this is handled. In JSON-LD/RDF this is quite clear, so the question is if and how to integrate that into the covjson structure.

**Comment by jonblower** [comment]
I think internationalisation would be a good thing - is there a problem with simply doing what JSON-LD does? (i.e. is there really a "how" question here?)

**Comment by neothemachine** [comment]
Well there are [multiple ways](http://www.w3.org/TR/json-ld/#string-internationalization) in JSON-LD. The following are relevant for us:
a map:
```js
{
  "@context":
  {
    ...
    "occupation": { "@id": "ex:occupation", "@container": "@language" }
  },
  "occupation":
  {
    "en": "Scientist",
    "de": "Wissenschaftler"
  }
  ...
}
```

an array (value and language could be aliased to value and lang):
```js
{
  "occupation": [{
    "@value": "Scientist",
    "@language": "en"
  },
  {
    "@value": "Wissenschaftler",
    "@language": "de"
  }]
}
```

So, we could say by default everything is english (and the context would have that default), and for other languages you have to use the map-form (the array form is too verbose I think). And we could require that an english string must always be given in that case.

**Comment by jonblower** [comment]
Makes sense - is there any precedent we could follow here?

Also, I can see that this makes clients a bit more complicated:
```js
var occupation;
if (internationalised) {
  occupation = data.occupation['en'];
} else {
  occupation = data.occupation;
}
```

Is that right or is there something we can do to make things simpler?

**Comment by neothemachine** [comment]
It could be made a requirement (with "en" required at minimum) for any labels that we define, like for parameter description, observedProperty label. So, that at minimum you must have:
```js
{
  "occupation":
  {
    "en": "Scientist"
  }
}
```
Then clients could ignore internationalization and just use `occupation.en` and ignore any other possibly defined translations.

**Comment by jonblower** [comment]
Yes, I can't see a better alternative to this.
