### ISSUE TITLE
Unit symbol should not be optional if unit is given

### ISSUE THREAD

**Issue by neothemachine** [Reading-eScience-Centre/coveragejson#18]
Currently the spec says that if "unit" is given, then it must have either or both "symbol" and "label". What was the rationale in having only "label"? Doesn't "symbol" always exist if a unit exists?

**Comment by jonblower** [comment]
I suppose a symbol always exists. But I wonder if it is sometimes not known? A symbol is a string that must be interpreted in the context of a certain set of rules (e.g. UCUM). It may be that for strange units, there is no established set of rules and the fallback position would be to use a label, which is used for display purposes but not intended to be used formally.

(I think it's generally true in RDF descriptions that very few properties are really compulsory. The open-world assumption means that if a property is missing, it is regarded as "unknown".)
