### ISSUE TITLE
LDP says rdfs:label should only be used in vocabulary documents

### ISSUE THREAD

**Issue by neothemachine** [Reading-eScience-Centre/coveragejson#19]
In the [best practices of LDP](http://www.w3.org/TR/ldp-bp/#common-properties) it says for rdfs:label "Only use this in vocabulary documents, to define the name of the vocabulary term." Currently we use it for various labels. Should we switch to dct:title?

**Comment by jonblower** [comment]
I didn't know that! I've seen rdfs:label used in all kinds of places. I might raise this with some of the W3C folk. I thought dct:title was more like the title of a document?

**Comment by neothemachine** [comment]
There's also [skos:prefLabel](http://www.w3.org/TR/skos-primer/) which seems to fit perfectly things like observedProperty or category labels. And skos:prefLabel is a subproperty of rdfs:label, so no idea why LDP is so strict about that.

**Comment by neothemachine** [comment]
Switched to skos:prefLabel, see http://patterns.dataincubator.org/book/preferred-label.html
