### ISSUE TITLE
How to define spatial (incl. vertical) CRS?

### ISSUE THREAD

**Issue by neothemachine** [Reading-eScience-Centre/coveragejson#2]
We need to describe how to define one (or two?) CRS for x, y, z.

Let's focus on a common case, WGS84 with lon-lat-heightaboveellipsoid order. Even for this simple case there is no CRS URI defined currently. The closest one is http://www.opengis.net/def/crs/OGC/1.3/CRS84 which has lon-lat order but is 2D only. It seems common referencable definitions of vertical CRSs don't exist (yet?). Since there are 3D CRS's the obvious question is whether we need vertical CRSs at all or whether compound 3D CRSs can be used.

**Comment by jonblower** [comment]
My instinct is to recommend using separate x-y and z CRSs. The infrastructure for x-y CRSs is fairly well established so we can use EPSG codes and various tools that interpret them. For z CRSs, the situation is not so clear. We may even have to mint some URIs of our own for unusual cases (e.g. pressure-based coordinates) although someone will surely one day do this properly.

Strictly speaking, you shouldn't mix vertical and horizontal CRSs arbitrarily. For an ellipsoidal x-y CRS you should only use ellipsoidal height, otherwise the vertical and horizontal CRSs are not orthogonal. But in practice people do this all the time (e.g. WGS84 CRS with pressure-based altitude) so we can probably allow it. (Geotoolkit also allows vertical and horizontal CRSs to be separable.)

**Comment by jonblower** [comment]
Can we use the context to create short aliases for CRS URIs, so that, for example, we could use "CRS:84" instead of "http://www.opengis.net/def/crs/OGC/1.3/CRS84"?

Also, it might be useful to recommend using a human-readable label for the CRS for GUI display purposes, although this could also be looked up from a database at application level.

**Comment by neothemachine** [comment]
Apparently shortcutting in subjects and objects only works when you use a colon ("If the prefix is not defined in the active context, or the suffix begins with two slashes (such as in http://example.com), the value is interpreted as absolute IRI instead."):
```js
{
  "@context":
  {
    "crs": { "@id": "http://coveragejson/crs", "@type": "@id" },
    "CRS": "http://www.opengis.net/def/crs/OGC/1.3/CRS",
  },
  "@id": "http://foo/",
  "crs": "CRS:84"
}
```
If you directly have `"CRS84": "http://www.opengis.net/def/crs/OGC/1.3/CRS84"` in the context with `"crs": "CRS84"`, it doesn't work. So I'm not sure about the value of that, considering that CRS:84 may be the standard one that will be omitted and any other ones will not use the CRS: prefix.

**Comment by jonblower** [comment]
Fair enough, let's forget the shortcutting then.

**Comment by neothemachine** [comment]
Some vertical CRS examples (by Jon):

1. “[distance above/below datum]”, e.g. “metres below mean sea level”, “metres below instantaneous sea level”, “metres above named ellipsoid”, “metres above named geoid”.

2. Pressure coordinates

3. Relative to moving platforms, e.g. ships (maybe this is a subtype of instantaneous sea level)

Some of these probably have EPSG codes.

**Comment by neothemachine** [comment]
Direct translation of [WKT](http://docs.opengeospatial.org/is/12-063r5/12-063r5.html) to JSON (imagine URLs at appropriate places):
```js
// horizontal CRS
"crs": {
  "name": "Foobar",
  "type": "GeodeticCRS",
  "id": "http://...",
  "datum": {
    "type": "Ellipsoid",
    "name": "GRS 1980",
    "semimajor": 6378137,
    "inverseflattening": 298.257222101,
    "unit": {
      "name": "metre",
      "conversionfactor": 1.0
    }
  },
  "cs": {
    "type": "EllipsoidalCS",
    "dimension": 2,
    "axes": [{
      "name": "Longitude",
      "abbrev": "lon",
      "direction": "east",
      "unit": {
        "type": "Angle",
        "name": "degree",
        "conversionfactor": 0.0174532925199433
      }
    }, {
      "name": "Latitude",
      "abbrev": "lat",
      "direction": "north",
      "unit": {
        "type": "Angle",
        "name": "degree",
        "conversionfactor": 0.0174532925199433
      }
    }]
  }
}

// vertical CRS
"crs": {
  "type": "VerticalCRS",
  "datum": {
    "type": "VerticalDatum",
    "id": "...",
    "name": "North American Vertical Datum 1988"
  },
  "cs": {
    "type": "VerticalCS",
    "dimension": 1,
    "axes": [{
      "name": "gravity-related height (H)",
      "direction": "up",
      "unit": "metre"
    }]
  }
}
```

The translation is pretty straight-forward. Looks pretty verbose to me but that's probably just how it is. Simple CRS84-only clients could inspect the URIs of the CRS object at the root and be done with it and ignore the rest. The path to get labels is also pretty easy... `crs.cs.axes[0].name`.

**Comment by jonblower** [comment]
Yes, it looks (probably necessarily) complex but reasonable. Looks like a syntax that would ultimately be generally useful, and could be standardised through OGC. But I think WKT is being updated so it could be a moving target...

Could we allow documents to provide just the URL of the CRS and allow clients to look them up? This could be convenient for common cases (e.g. CRS84), although perhaps not generally recommended.

What about CRSs that can't be expressed in WKT? Would these be "engineering CRSs" with some application-specific metadata? I'm thinking of curvilinear systems and stuff here.

**Comment by neothemachine** [comment]
I said earlier that it's not possible to alias URIs so that we can use `"crs": "CRS84"` but it turns out I was wrong. A really hidden feature in JSON-LD allows that actually!

```js
{
  "@context": {
    "crs": {"@id": "http://../hasCrs", "@type": "@vocab"},
    "CRS84": "http://www.opengis.net/def/crs/OGC/1.3/CRS84"
  },
  "crs": "CRS84"
}
```

Reference: https://github.com/lanthaler/JsonLD/issues/31

**Comment by neothemachine** [comment]
Jon, the pressure based vertical reference system you mention sometimes, can you check if there's a WKT for that? Then I can translate it more easily.  If not, we should [create a WKT](http://docs.opengeospatial.org/is/12-063r5/12-063r5.html#69) first.

Here's an example:
```
VERTCRS[“NAVD88”,
     VDATUM[“North American Vertical Datum 1988”],
     CS[vertical,1],
       AXIS["gravity-related height (H)“,up],LENGTHUNIT[”metre",1.0]
]
```

**Comment by neothemachine** [comment]
I currently use the following for pressure-based vertical profiles:

```js
      "srs": {
        "type": "VerticalCRS",
        "cs": {
          "axes": [{
            "name": {
              "en": "Pressure"
            },
            "direction": "down",
            "unit": {
              "symbol": "Pa"
            }
          }]
        }
      }
```

But I'm not sure if this is right, since I found the following WKT example:
```

**Comment by jonblower** [comment]
I'm not sure that a pressure-based coordinate would have a datum. Zero pressure would be outside the atmosphere. It's a system based on absolute values, not values relative to a reference value.

**Comment by neothemachine** [comment]
Makes sense. I'll close this now since I added the vertical CRS example to the spec. Any future advanced CRS definitions go into a new issue.
