### ISSUE TITLE
Embedded Domain and Range objects should have ID if linked data is embraced

### ISSUE THREAD

**Issue by neothemachine** [Reading-eScience-Centre/coveragejson#21]
In the [Linked Data Platform](http://www.w3.org/TR/ldp/) recommendation there is a clear distinction between RDF and non-RDF resources, but not so much RDF resources which include non-RDF things, conveniently possible with JSON-LD. To close the circle I propose that when a domain or range object is embedded in a CoverageJSON coverage or coverage collection document and it is served by a web server with LD context then the domain and range/s should also be made available under separate URLs and these URLs should then be included as "id" properties in the embedded objects. Then, pure RDF clients (which would throw away all non-RDF fields) still have the chance to see the URLs of the domain and range and may assert that this is a non-RDF resource where the traversal ends for them. And if this is ingested in some RDF store then it would even be possible to fetch the domain and range parts as CoverageJSON documents and have the individual CoverageJSON coverage objects ingested as standard RDF triples.

This assumes that the CoverageJSON coverage and coverage collection documents are also published under the JSON-LD content type (or turtle) via content negotiation which regular RDF clients would request. The domain and range would only be served with the CoverageJSON (json|binary) document type.

**Comment by jonblower** [comment]
Makes sense to me overall. Not quite sure of the implications of using separate content types for the "main" CoverageJSON document and the domain/range documents.

**Comment by neothemachine** [comment]
It's not separate, just additional. Domain and range are only exposed via conneg as covjson content type. Coverage and collection are exposed as covjson content type but also as some rdf-like content type.

**Comment by jonblower** [comment]
Right, OK. For Coverage and Collection, would you get the same actual document content back, whether it's JSON-LD or .covjson?

**Comment by neothemachine** [comment]
I guess so.
