### ISSUE TITLE
What is the meaning of "id" for categories? / where to put category value encoding

### ISSUE THREAD

**Issue by neothemachine** [Reading-eScience-Centre/coveragejson#26]
A category within a parameter can have an "id" field and this is probably the actual category concept that is used, so some URI which defines that category, independent of how the data is encoded. The "label" and "description"  make sense, they are on the same conceptual level. However, the "value/s" is actually not a property of the category itself, but more of the encoding of it in this particular coverage/parameter. And because of that you would never say that the given category URI hasValue 1, in RDF. 

Should we ignore that slight inconsistency, given that "value/s" is not published as RDF anyway? I can't think of a convenient other structure which would resolve that. Something like that is a bit ugly:
```js
  "categories": [
    {
      "id": "http://.../landcover1/categories/grass",
      "label": {
        "en": "Grass"
      },
    }, {
      "id": "http://.../landcover1/categories/forest",
      "label": {
        "en": "Forest"
      }
    }, ...
  ],
  "categoryMapping": [
    {
      "category": "http://.../landcover1/categories/grass",
      "value": 1
    }, {
      "category": "http://.../landcover1/categories/forest",
      "values": [2,3]
   }
  ]
```
This would also make IDs mandatory.

**Comment by jonblower** [comment]
I'm not sure what the solution is, but I note that this is a similar situation to the "validMin" and "validMax" properties of a field with continuous values. These properties are also a function of the encoding, not the concept of the parameter.

It could be worth separating "concept" from "encoding" details as you sketch above, but this could introduce more complexity.

Also, your `categoryMapping` structure above reminds me of the work @guygriffiths is doing on creating an app to remap classifications from one scheme to another. You might be able to end up at the same syntax.

**Comment by jonblower** [comment]
Also, it's probably a good idea for ids to be mandatory anyway, but I suppose they don't have to be URLs, where a URL definition is not known?

**Comment by neothemachine** [comment]
The "validMin" and "validMax" are currently not part of the parameter but of the range object (which contains the encoding information), so that seems to fit.
I agree that mandatory IDs for categories, even if not URIs, make sense. This becomes more important when thinking about things like external category mappings, default styling etc.

Now, the tricky part, where to put the values for each category. I actually think they would fit into the range object as well, so just that part:
```js
  "categoryMapping": [
    {
      "category": "http://.../landcover1/categories/grass",
      "value": 1
    }, {
      "category": "http://.../landcover1/categories/forest",
      "values": [2,3]
   }
  ]
```
Then you could still construct your legend etc just from the Parameter and when you get the range data you look at the category mapping to see how the categories are really encoded. It's not that different than saying "each range value directly maps to a measured value" or "each range value is encoded as offset/factor".

Do you agree?

**Comment by jonblower** [comment]
Yes, I think this is a valid and consistent approach. Separating the "concept" from the "encoding" enables a nice separation of concerns in my view, and there are different use cases for each. For example, certain types of statistics can be calculated purely using the Range object (e.g. percentage of pixels in each class).

**Comment by neothemachine** [comment]
OK, I played through several scenarios in my head to see how much this would complicate everything in terms of usage, remapping etc. There is a slight overhead but the advantages are very clear. It actually drives you to develop more in terms of the concept (category IDs) instead of raw numbers, since the category (with ID) is the only thing you got before you would retrieve the range. It also allows to use such a categorical parameter for multiple coverages (e.g. in a collection) where each can have its own encoding of the category numbers. And this makes the parameter object truly reusable again, outside of coveragejson even, since you may encode categories even with plain strings etc. So, +1 that all this makes sense. I will however wait a bit and do it after Bologna since this involves some breaking changes and Guy is using categories already.

**Comment by jonblower** [comment]
makes sense.

**Comment by neothemachine** [comment]
I just found a contra argument for putting the category mappings inside the range. When you would use CoverageJSON for tiling, the actual tiles would be URLs pointing to range documents. And would you want to have your 50 category mappings in each and every of those tiles?

**Comment by jonblower** [comment]
Hm, I see. But I guess the category mapping would usually be much smaller than the range data for a tile?

**Comment by neothemachine** [comment]
Not necessarily, let's say you have 256x256 tiles, and let's assume each range value takes up one byte, then you have 64KiB. For 50 categories with URL length of 100 chars, you get around 5KiB extra for each tile. Of course, this is before gzip, but still. I will think about it a bit more.

**Comment by neothemachine** [comment]
After a chat with Adam Leadbetter: The categories belong inside the observedProperty (which then is a "complex property"). The mapping to range values does not belong there, and could either go into the parameter itself or the range.

**Comment by neothemachine** [comment]
I'm still not sure about including the category mapping inside the range. If you say that the mapping relates a value to its actual concept, then what about units? Units relate numbers to a physical quantity, so do they belong to the range as well? You could argue that the parameter only includes the canonical units and the actual units of measurement inside the range are just one of the encodings/variants of the canonical units. And once we go down that path it is hard to stop and gets ugly quickly. I think we should be pragmatic about it and just say that these things belong to the parameter itself, and if you have another land cover grid with the same categories but which encodes values differently, well then you just have a different parameter but with the same observedProperty (which includes the categories). It's just easier to deal with from a client perspective than being forced to defer all that logic until you load the range. You could of course argue that offset/factor encoding then belongs to the parameter as well, but I see this as a separate low-level layer, like gzip compression of the data.

I'm still open to be convinced otherwise but currently I can't see any real advantage in splitting these things around.

**Comment by jonblower** [comment]
I agree. I think including the units and mapping with the Parameter is more intuitively obvious and to do otherwise might be surprising to users.
