### ISSUE TITLE
Use of different unit vocabularies in one document

### ISSUE THREAD

**Issue by neothemachine** [Reading-eScience-Centre/coveragejson#27]
Currently, there is a fixed structure for referencing units:
```js
      "unit" : {
        "symbol" : "K"
      }
```
where the vocabulary can optionally be defined in the JSON-LD context: 
```js
"@context" : {
    "qudt" : "http://qudt.org/1.1/schema/qudt#",
    "unit" : "qudt:unit",
    "symbol" : "qudt:symbol"
  }
```

However, it may be a valid use case to aggregate multiple CoverageJSON coverages from different sources in a single collection document. This would require unifying the units if they used different unit vocabularies, which is in general a hard task, or even impossible if the units don't exist in all vocabularies.

How can this be solved?

**Comment by jonblower** [comment]
Not sure there is a solution to this. I'm not sure whether we'll really need to aggregate multiple coverages from different sources in the same document - when would this happen? If it did happen I guess we would have to harmonise units somehow.

**Comment by neothemachine** [comment]
Just found the solution. You can have multiple contexts in a document where the inner ones override the outer ones. So, to use a different unit vocabulary, you could just do:

```js
{
  "@context": {
    "unit" : "http://.../unit",
    "symbol" : "http://.../symbol"
  },   
  "unit" : {
    "symbol" : "K"
  }
}
```
