### ISSUE TITLE
geometryType -> valueType/dataType; also: axis vs dimension

### ISSUE THREAD

**Issue by neothemachine** [Reading-eScience-Centre/coveragejson#33]
Since "values" instead of "coordinates" shall be used for axis objects (see https://github.com/Reading-eScience-Centre/coveragejson/issues/3#issuecomment-157101428) it makes sense to generalize the term "geometryType" to "valueType". Especially since the default geometryType of Coordinate wouldn't fit to time strings. So instead of thinking of spatial geometry types, we could think of data structure types. The default could be "Simple" (before, it was "Coordinate") and anything else is "Complex" (abstract type). Instead of "Simple" it could be "Primitive" but I don't like that really. The actual values that would be used are "SimpleComposite" (array of simple values) and "Polygon" (a GeoJSON-like Polygon coordinates array).

**Comment by neothemachine** [comment]
Renamed it to "compositeType" which can be either "Simple", "Polygon", or a custom URI.

**Comment by jonblower** [comment]
I'm not sure I've understood this. Would "compositeType" make sense where the axis values are not composites? Are the use cases:
 * Numeric (e.g. latitude, longitude, time in a temporal CRS)
 * Time instant (i.e. ISO-like string)
 * Tuple (e.g. for trajectories)
 * Polygon

or have I misunderstood the intention of this?

**Comment by neothemachine** [comment]
Axis values are either primitive (number, string[, bool, null]) or composite (anything else). The use case is just to identify the structure of the values, not their semantics. And the use case for understanding their structure is to properly create a connection to the reference systems when they refer to axis/component identifiers. If compositeType does not exist, then the values are primitive. If it does exist, they are composite and the type further defines the structure. Currently, "compositeType" can be "Simple" which means a tuple/array of primitive values, or "Polygon" for a GeoJSON polygon array.

**Comment by jonblower** [comment]
OK, that's clearer to me now, thanks. I'm still not sure that "Simple" is a good term for a tuple. Having a "simple composite" seems almost like a contradiction in terms. Would "tuple" suffice?

**Comment by neothemachine** [comment]
My only worry is that "tuple" in general also covers tuples of composite values, but here we want to restrict it to tuples of primitive values. But I agree, it may still be confusing at the moment.

**Comment by neothemachine** [comment]
Reopening, need better terminology.

**Comment by neothemachine** [comment]
I renamed "Simple" to "Vector". Even though the mathematical notion is broader than what we allow here (only primitive vector elements) I think it still makes sense. If in the future there is a need for have an array or object as one of the vector components, then we could still invent a "ComplexVector" for that. Do you agree? Then I would close this issue.

**Comment by neothemachine** [comment]
Scrap that, Vector doesn't actually fit from a mathematical point of view (axioms etc.), I renamed it to Tuple now which should work for all cases.

**Comment by neothemachine** [comment]
OK, I think I finally got it right now. I renamed compositeType to dataType, and more importantly "components" to "dimensions". Components worked fine for tuples, but not really for polygons or other structures, and referencing components in reference systems was also a bit weird. I think dimension is the correct term here. It just feels right and it is way easier to understand as a concept.

Also note that this now has uniform definitions also for non-composite values. In that case, the dataType is implicitly "Primitive" and the "dimensions" are a single dimension of the same name as the axis key. This is a default and I have a requirement in the spec that in the default case the axis object is not allowed to explicitly include the dataType and dimensions, to have consistent documents.

**Comment by neothemachine** [comment]
See the updated spec, [section 6.1](https://github.com/Reading-eScience-Centre/coveragejson/blob/master/spec.md#61-domain-objects)

**Comment by jonblower** [comment]
Yes, this makes sense to me now. It would be good (if not done already) to discuss this some more in the spec. If I'm reading this correctly, a _dimension_ is a spatiotemporal (xyzt) dimension, and corresponds with coordinate referencing information. An _axis_ is a component of the domain, orthogonal to all other axes. An axis may correspond with a dimension, but may be comprised of coordinates from many dimensions (hence a trajectory is a 1-axis feature in a 4-dimensional space).

One could also argue that this terminology should be reversed, which might actually match other systems better. (In NetCDF a _dimension_ is a side of the data cube, whereas we are calling this an axis. And coordinate reference systems are comprised of _axes_ in the usual GIS terminology.)

**Comment by neothemachine** [comment]
Your interpretation is right.

Regarding dimension vs axis:
- CIS uses axis in CRSs, but also defines srsDimension as "The number of named axes in
the CRS". CIS uses axis for grids as well, and a grid also has a dimension (number of axes). So axis is used for both cases. Dimension is just a number. CIS uses the [physical/mathematical definitions of axis and dimension (of a space)](https://en.wikipedia.org/wiki/Dimension).
- NetCDF has the concept of dimension which defines an internal name and the size of it but not any coordinate values or semantics. The NetCDF-CF document also uses the term axis for the actual coordinate variable if it is 1D. Since dimensions themselves don't have any meaning on their own except defining a size I'm not sure if they match our current domain axes so well, at least in the netCDF sense. NetCDF uses the ["dimension of an object" definition](https://en.wikipedia.org/wiki/Size) for dimension.
- [RDF Data Cube](https://www.w3.org/TR/vocab-data-cube/) uses the term dimension and doesn't know axis. It uses the ["dimension is a structure that categorizes facts and measures" definition (data warehouse)](https://en.wikipedia.org/wiki/Dimension_%28data_warehouse%29). Notably, the dimension values are not ordered!
- Currently, in CovJSON, for a tuple axis, the individual components are matched to CRS axes via `"dimensions": ["t", "x", "y"]`. If the terms are switched, then this would be `"axes": ["t", "x", "y"]` which may be slightly confusing as someone could assume that each of the components in the array of tuples forms an axis (with ordered values), which is not the case. The word dimensions doesn't carry this meaning in any of the previously referenced definitions.
- Even though axis is typically used in CRSs, we are more general and allow any reference system, not necessarily based on coordinates. It feels like an axis is a specialisation of a data warehouse dimension with additional constraints. If the reference system is e.g. ISO 3166-1 alpha-2, then the axis values would be 2-letter country codes like ["DE", "GB"] and clearly there is no axis with a defined order but just the set of codes which one could say are in the 1-dimensional space of ISO 3166-1 alpha-2 country codes.

I'm sure some of that is debatable or slightly wrong/incorrect in some contexts but what I found interesting is that dimension does not have an ordering in any definition or use, whereas axis does. Since our domain axis values do have an ordering I think using "dimensions" would be wrong here. I agree that referring CRS axes via "dimensions" is not as precise as it could be, but as I wrote above we are more general, so it would be wrong in some cases if the reference system does not have a value ordering. CIS seems to be restricted to spatiotemporal CRSs, so the obvious question is: Do we really want to be more general? If yes, then this has to be added to the CIS section of the spec. And I guess we do, right?

**Comment by jonblower** [comment]
Consider the case of encoding a trajectory in NetCDF. You'd have a single _dimension_, with several coordinate arrays that depend on that dimension. Each of these coordinate arrays corresponds with an axis in a CRS. But in the current CovJSON the terminology would be reversed: there would be a single "axis" with a link to multiple "dimensions". A trajectory is a one-dimensional object in a multidimensional space.

> may be slightly confusing as someone could assume that each of the components in the array of tuples forms an axis (with ordered values), which is not the case.

There's a difference between an axis _definition_ (that you'd find in a CRS definition) and a concrete instantiation of an axis, which is the list of axis values. What about having `"coordinateAxes": ["t", "x", "y"]`?

**Comment by neothemachine** [comment]
For grids, we talk about things like regular axes. Would you then say regular dimensions? Doesn't seem right to me and also doesn't match CIS, which defines regular and irregular axes for grids.

**Comment by jonblower** [comment]
No, "regular dimension" would not make sense. There would be a regular _axis_, which lines up with the corresponding dimension. The axis would be associated with a "coordinate axis", i.e. a component of a CRS.

On reflection, I'm wondering if the concept of a dimension (in the NetCDF sense) needs to appear in CovJSON at all. It's given implicitly by the axes. (The structure of NetCDF means that the dimension construct is necessary but maybe it's not necessary in JSON, where we can nest things.)

But I'm still not quite happy with using the word "dimension" to mean a link to a reference system. That doesn't quite make sense to me (both because of NetCDF usage and English meaning!). How about using "axisReference" or "axisLink" if the purpose is to link the axis values to reference systems?

You are right to introduce the use case of (potentially unordered) non-spatiotemporal axes, which is why I'm not quite comfortable with "coordinateAxis". 

I think this may be the sort of thing that's best explained by example...

**Comment by neothemachine** [comment]
The problem is that we have to cover arbitrary axis value data types. And a data type currently defines which dimensions it exposes under which aliases (currently just for referencing), e.g. the components of a tuple, or the coordinate parts of each polygon point. In that sense it's decoupled from reference systems, meaning that we don't directly use e.g. the CRS axis abbreviation (e.g. "lat") like CIS does (which is only defined for CRSs and not other reference system types). So, currently the domain axes expose dimension names, and the "referencing" property references these which are then matched up to dimensions exposed by the reference system according to some rules (e.g. for CRS, axes = dimensions; for temporal rs, single dimension only; ...).

But I agree it may be confusing and not understandable by just looking at it. I really don't know how to do it differently though while considering all cases. How would you call the things inside a tupled axis (=set of all x values across all tuples for example) if not dimension? Only then we can think about how to refer to this concept for referencing systems.

**Comment by jonblower** [comment]
How about "components"? I don't think we're using that term elsewhere in CovJSON.

I also thought about "elements" but that might be confused with the elements of a list or collection.

**Comment by neothemachine** [comment]
I actually had it as "components" [before renaming it to "dimensions"](https://github.com/Reading-eScience-Centre/coveragejson/issues/33#issuecomment-174171753). I had written "Components worked fine for tuples, but not really for polygons or other structures, and referencing components in reference systems was also a bit weird. " We're not using "components" currently elsewhere.

I also changed it to "dimensions" because I thought "components" is yet another new concept whereas dimensions could be reused.

**Comment by jonblower** [comment]
Well it could be a case of "potato potahto" if you're familiar with that saying! But to be honest, the more I think about it the more I like "components". A composite axis is a list of tuples, and each item in that list is a list of values of its _components_. That terminology feels natural to me. "Dimensions" could work, but in my mind that is an overloaded term and the first thing that comes into my head is a physical dimension. "Component" feels more neutral and could equally well apply to non-spatiotemporal, er, axes.

> referencing components in reference systems was also a bit weird

I don't think referencing "dimensions" in reference systems is any less weird, considering that most reference systems are made up of axes.

**Comment by neothemachine** [comment]
I know that saying from the song "Let's Call The Whole Thing Off" actually!
I think I can live with "components". So does the following make sense for primitive axes?

```js
  "domain" : {
    "type": "Domain",
    "profile": "Grid",
    "axes": {
      "x": { "start": -179.5, "stop": 179.5, "num": 360 },
      "y": { "start": -89.5, "stop": 89.5, "num": 180 },
      "t": { "values": ["2013-01-13T00:00:00Z"] }
    },
    "rangeAxisOrder": ["t","y","x"],
    "referencing": [{
      "components": ["x","y"],
      "srs": {
        "type": "GeodeticCRS",
        "id": "http://www.opengis.net/def/crs/OGC/1.3/CRS84"        
      }
    }, {
      "components": ["t"],
      "trs": {
        "type": "TemporalRS",
        "calendar": "Gregorian"
      }
    }]
  },
```

Similarly, for polygons:
```js
  "domain" : {
    "type": "Domain",
    "axes": {
      "composite": {
        "dataType": "Polygon",
        "components": ["x","y"],
        "values": [
          [ [ [100.0, 0.0], [101.0, 0.0], [101.0, 1.0], [100.0, 1.0], [100.0, 0.0] ]  ]
        ]
      }
    },
    "referencing": [{
      "components": ["x","y"],
      "srs": {
        "type": "GeodeticCRS",
        "id": "http://www.opengis.net/def/crs/OGC/1.3/CRS84"        
      }
    }
  },
```

**Comment by jonblower** [comment]
That makes sense to me. Would be interesting to see the case for a non-spatiotemporal axis (like country codes). I think it would be OK.

**Comment by neothemachine** [comment]
Actually, country codes would also be a spatial ref system (according to [ISO19112](http://people.ischool.berkeley.edu/~ryanshaw/pdf/ISO_19112.pdf)), so also a spatial axis. Something like:
```js
  "domain" : {
    "type": "Domain",
    "axes": {
      "country": {
        "values": [ "de", "gb" ]
      }
    },
    "referencing": [{
      "components": ["country"],
      "srs": {
        "type": "GeographicIdentifierRS",
        "id": "https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2",
        // optional for convenience
        "identifiers": {
          "de": {
            "id": "http://dbpedia.org/resource/Germany",
            "label": { "de": "Deutschland", "en": "Germany" },
            "spatialExtent": [...] // bbox
          },
          "gb": {
            "id": "http://dbpedia.org/resource/United_Kingdom",
            "label": { "de": "Vereinigtes Königreich", "en": "United Kingdom" },
            "spatialExtent": [...] // bbox
          }
        }
      }
    }
  },
```
By the way, I like how this merges the code based with the linked data world.

I can't think of any non-spatiotemporal axis right now but it seems to work anyway.

**Comment by jonblower** [comment]
Looks very good to me. An example of a non-spatiotemporal axis might be “Gender”, if we were interested in, say, life expectancy data per country. This matches with the examples they give for the RDF Data Cube and it might be a useful exercise to compare the CoverageJSON encoding with the DataCube encoding.

**Comment by neothemachine** [comment]
I guess what I would do is generalize GeographicIdentifierRS to just IdentifierRS and do that:
```js
  "domain" : {
    "type": "Domain",
    "axes": {
      "gender": {
        "values": [ "m", "f" ]
      }
    },
    "referencing": [{
      "components": ["gender"],
      "rs": { // Not srs anymore!
        "type": "IdentifierRS",
        // this probably should not be "id" since it is not a ref system as such
        "id": "http://dbpedia.org/ontology/gender",
        // required I guess
        "identifiers": {
          "m": {
            "id": "http://dbpedia.org/resource/Male",
            "label": { "de": "Männlich", "en": "Male" }
          },
          "f": {
            "id": "http://dbpedia.org/resource/Female",
            "label": { "de": "Weiblich", "en": "Female" }
          }
        }
      }
    }
  },
```
So, here codes are referenced to non-geographic concepts.


Of course you could also directly go to URI space:
```js
  "domain" : {
    "type": "Domain",
    "axes": {
      "gender": {
        "values": [ "http://dbpedia.org/resource/Male", "http://dbpedia.org/resource/Female" ]
      }
    },
    "referencing": [{
      "components": ["gender"],
      "rs": { // Not srs anymore!
        "type": "UniformResourceIdentifierRS", // subtype of IdentifierRS
        // this probably should not be "id" since it is not a ref system as such
        "id": "http://dbpedia.org/ontology/gender",
        // required I guess
        "identifiers": {
          "http://dbpedia.org/resource/Male": {
            "id": "http://dbpedia.org/resource/Male",
            "label": { "de": "Männlich", "en": "Male" }
          },
          "http://dbpedia.org/resource/Female": {
            "id": "http://dbpedia.org/resource/Female",
            "label": { "de": "Weiblich", "en": "Female" }
          }
        }
      }
    }
  },
```
What does this URI ref system reference? A URI already represents a concept, so this would just establish further information about the concepts? Could you still call that a reference system then?

**Comment by neothemachine** [comment]
So, just to come back to the original topic: Does "components" make sense in all the earlier examples?

In the CIS comparison, there is currently:
> CIS enforces exactly one coordinate reference system (CRS) per coverage, CoverageJSON allows CRSs to be associated with a given combination of dimensions.

How would we rewrite that? Just replacing it with components doesn't make much sense on its own. And saying "axes" would be wrong in the general sense.

The spec text would change to the following (replaced "dimension" with "component"):

6.1.1. Axis Objects
...
- The value of "dataType" determines the structure of an axis value and its components that are made available for referencing. The value of "dataType" must be either "Primitive", "Tuple", "Polygon", or a full custom URI (although custom data types are not recommended for interoperability reasons). For "Primitive", there is a single component and each axis value must be a number or string. For "Tuple", each axis value must be an array of fixed size of primitive values in a defined order, where the tuple size corresponds to the number of components. For "Polygon", each axis value must be a GeoJSON Polygon coordinate array, where each of the coordinate components (e.g. the x coordinates) form a component in the order they appear.
- If missing, the member "dataType" defaults to "Primitive" and must not be included for that default case.
- If "dataType" is "Primitive" and the associated reference system (see 6.1.2) defines a natural ordering of values then the array values must be ordered monotonically, that is, increasing or decreasing.
- The value of "components" is a non-empty array of component identifiers corresponding to the order of the components defined by "dataType".
- If missing, the member "components" defaults to a one-element array of the axis identifier and must not be included for that default case.
- A component identifier shall not be defined more than once in all axis objects of a domain object.

6.1.2. Reference System Connection Objects

A reference system connection object creates a link between values within domain axes and a reference system to be able to interpret those values, e.g. as coordinates in a certain coordinate reference system.

- A reference system connection object must have a member "components" which has as value an array of component identifiers that are referenced in this object. Depending on the type of referencing, the ordering of the identifiers may be relevant, e.g. for 2D/3D coordinate reference systems.
- A reference system connection object must have exactly one of the members "srs", "trs", or "rs", where "srs" has as value a spatial reference system object, "trs" a temporal reference system object, and "rs" a reference system object that is neither spatial nor temporal. Section 5 defines common types of spatial and temporal reference system objects.

**Comment by jonblower** [comment]
> How would we rewrite that? Just replacing it with components doesn't make much sense on its own. And saying "axes" would be wrong in the general sense.

Well, the only way I can think to address this is to define "components" earlier and then use the word components here. Anything else would seem inconsistent.

I think the rest of the text is fine (at least, I can't think of a better way to do it). My only question is over the use of "srs", "trs" and "rs" - do we need to distinguish them? Would it do any harm if they were all "rs", and in fact might that be easier for clients?

**Comment by neothemachine** [comment]
OK, I will change it from "dimensions" to "components" then. Also, as we discussed today, there is no harm in collapsing "srs"/"trs"/"rs" into a single one, since this is also what I do in the JS API and there's no issue with that. Should it be "rs" then or something longer? "system" (I use that in the JS API)? "refSystem"?

**Comment by jonblower** [comment]
I think "system" is good - it pairs nicely with the parent "referencing" element
