### ISSUE TITLE
Use simpler example in introduction

### ISSUE THREAD

**Issue by neothemachine** [Reading-eScience-Centre/coveragejson#35]
The introduction should have a simple grid example since this is what most people are familiar with and it prevents introducing the complexity of vertical CRSs. Any ideas for such an example? Which parameters, how big etc.?

**Comment by jonblower** [comment]
I would suggest a global lat-lon grid at 1 degree resolution (360x180 points), e.g. global temperature. Do you think we should use regular axis shorthand here too or spell out the lon and lat axis values?


I’d suggest an ocean dataset as it would also show the use of “fill values” to represent land pixels.

**Comment by neothemachine** [comment]
Hm, 360+180 numbers inside the domain would be too much json to show, so even though it is slightly more complicated, the regular axis encoding would probably be better.

Latitude would go from  -89.5 to 89.5 and longitude from -179.5 to 179.5 right?

**Comment by jonblower** [comment]
Right.
