### ISSUE TITLE
Should axisOrder only include varying axes?

### ISSUE THREAD

**Issue by neothemachine** [Reading-eScience-Centre/coveragejson#37]
When it is necessary to define an axis order for the range, then currently it is necessary (just because the definition says so) to include one-element axes as well. Example:

```js
{
  "type": "Grid",
  "axes": {
    "x": { "values": [1,2,3] },
    "y": { "values": [20,21] },
    "z": { "values": [1] },
    "t": { "values": ["2008-01-01T04:00:00Z"] }
  },
  "axisOrder": ["t","z","y","x"],
  "referencing": [...]
}
```

In theory it would be enough to define `["t","y","x"]`. The same applies to MultiPolygonSeries:

```js
{
  "type": "MultiPolygonSeries",
  "axes": {
    "composite": {
      "geometryType": "Polygon",
      "components": ["x","y"],
      "values": [
        [ [ [100.0, 0.0], [101.0, 0.0], [101.0, 1.0], [100.0, 1.0], [100.0, 0.0] ]  ],
        [ [ [200.0, 10.0], [201.0, 10.0], [201.0, 11.0], [200.0, 11.0], [200.0, 10.0] ] ]
      ]
    }
    "z": { "values": [2] },
    "t": { "values": ["2008-01-01T04:00:00Z", "2010-01-01T00:00:00Z"] }
  },
  "axisOrder": ["t","z","composite"],
  "referencing": [...]
}
```
Here, z is fixed. 

Note to self: Think about simple clients and how they want to access range data for the predefined domain types.

**Comment by jonblower** [comment]
I think the only reason (although I think it’s a good reason) to include single-valued axes is to stick to the principle of “least surprise”. It may seem odd to a user for some axes to be missing from the axisOrder list. But syntactically it doesn’t matter.

**Comment by neothemachine** [comment]
Ok, let's do that then, keeps definitions easier as well. And implementations as well I think (axis order missing -> take all axes in random order; axis order exists -> use the defined axes in that order (no need to fill up with other axes not in the array)).
