### ISSUE TITLE
Choose serialization format for units

### ISSUE THREAD

**Issue by neothemachine** [Reading-eScience-Centre/coveragejson#40]
Continuing from https://github.com/Reading-eScience-Centre/coveragejson/issues/39#issuecomment-158027115 we need to choose a serialization format for units (the `"symbol"` field). This has to be fixed and must be independent of whether the client uses LD (and hence unit URIs) or not. ~~Ideally, it would map to some ontology term that forces that specific serialization format.~~ (see first comment)

Candidates:
- [UCUM](http://unitsofmeasure.org/ucum.html)
- [UDUNITS2](http://www.unidata.ucar.edu/software/udunits/udunits-2.2.20/doc/udunits/udunits2.html) (could not find a proper documentation of the syntax)

Not helpful:
- [qudt](http://www.qudt.org/), it doesn't have a specific serialization format

Any others?

**Comment by neothemachine** [comment]
I take back what I said about the ontology term should force a serialization format. This is what the rdf literal value type is for. So, we could actually use `qudt:unit` and then have a string "something in ucum" with a type of "http://unitsofmeasure.org" for example.

**Comment by jonblower** [comment]
Yes, that's right. And we could allow xsd:string as a fallback in case there really is no known serialisation scheme.

**Comment by neothemachine** [comment]
We have to decide whether we want to force the type to be explicitly included every time units are given:
```js
"unit": {
  "symbol": {
    "value": "m^2"
    "type": "http://unitsofmeasure.org"
  }
}
```
And I'm pretty sure we don't. This on the other hand would mean that we would have to define a default symbol type. And If someone wants to use a different one, he has to do it like above, and by default it would in the form of `"symbol": "m^2"`.

**Comment by jonblower** [comment]
So perhaps xsd:string would be the default type? And does this mean that:

 `"symbol": "m^2"`

is interpreted as the same as

```
  "symbol": {
    "value": "m^2"
    "type": "xsd:string"
  }
```

or whatever the syntax is?

**Comment by neothemachine** [comment]
Yes, it would be interpreted like that. But what do we gain from making xsd:string the default?

**Comment by jonblower** [comment]
Ideally a stronger type would be used, but there's no obvious default. If a source file is CF-compliant then the unit string should be UDUNITS, but often this isn't the case. UCUM may be used by other communities but is by no means universal. Data providers often don't pay much attention to this and sometimes units are a bit ad-hoc. xsd:string will never be wrong - if we use another default the chances are that many files will be wrong, unintentionally.

I'd suggest using xsd:string as the default, but recommending a stronger type if it is known by the data provider. My second preference would be to have no default, but I think the shorthand syntax is useful.
