### ISSUE TITLE
Move pre-defined coverage/domain types into separate document?

### ISSUE THREAD

**Issue by neothemachine** [Reading-eScience-Centre/coveragejson#42]
Looking at https://github.com/Reading-eScience-Centre/coveragejson/issues/34#issuecomment-158034645, I wonder whether it would make sense to move the pre-defined coverage/domain types into a separate document. They currently make up about 1/4 of the spec length.

**Comment by jonblower** [comment]
Yes, I think that might be a good idea

**Comment by neothemachine** [comment]
done
