### ISSUE TITLE
Should multiple profiles be allowed?

### ISSUE THREAD

**Issue by neothemachine** [Reading-eScience-Centre/coveragejson#46]
Since the notion of profile corresponds to [RFC6909](https://www.ietf.org/rfc/rfc6906.txt) it would make sense to allow multiple profiles for a given coverage, domain, or collection. This would make it more flexible since people could combine our pre-defined profiles with more custom profiles if they want, without loosing interoperability by having to *replace* e.g. "TrajectoryCoverage" by "http://www.topografix.com/gpx#Track", but instead: `["TrajectoryCoverage", "http://www.topografix.com/gpx#Track"]`. OGC also defines a lot of profiles (though more for the API capabilities I think), so that may also be a factor.

I [changed the JS API](https://github.com/Reading-eScience-Centre/coverage-jsapi/blob/master/Coverage.md) to allow that and it makes sense to me.

Proposal:
Instead of
```js
{
  ...
  "profile": "GridCoverage",
  ...
}
```
it could be
```js
{
  ...
  "profiles": ["GridCoverage"],
  ...
}
```

**Comment by jonblower** [comment]
Sounds like a reasonable idea, but it would be good to see an example of how a Coverage might conform to many profiles (e.g. both a TrajectoryCoverage and a gpx#Track).

**Comment by neothemachine** [comment]
Note to self: Check how this relates to the "profile" media type parameter. Does that have the same purpose as the root level profiles of a covjson document?

**Comment by neothemachine** [comment]
Related: https://github.com/Reading-eScience-Centre/coveragejson/issues/58

**Comment by neothemachine** [comment]
Closing, as we settled on domainType now. Maybe profiles in the document become relevant in the future again.
