### ISSUE TITLE
Do we need validMin/validMax?

### ISSUE THREAD

**Issue by neothemachine** [Reading-eScience-Centre/coveragejson#48]
Currently, a range object may include validMin/validMax properties, but it is unclear what purpose these have since in JSON there is no need for a missing-value number encoding (=null). So the only purpose could be to give clients a hint about the possible value range and use that for legends, but since legends depend on context and user preference this is not that useful information in the end.

I therefore propose to either remove those properties or redefine them as actualMin/actualMax or something like that which would reflect the precise min/max value occuring in the data.

**Comment by jonblower** [comment]
I tend to agree. actualMin/Max should be optional, with a “health warning” that data providers should make sure that these are accurate. Maybe for v1 we could omit actualMin/Max and see if we need it?

The only reason for keeping validMin/Max is if we want to have several different kinds of missing values, which could be encoded as different out-of-range values. But this is probably much better handled as a mask field of some kind.

**Comment by neothemachine** [comment]
Ok, I will remove validMin/max then. About missing values, I agree it's better to use a regular parameter for that since then we have everything we need for free, like reason categories etc. Also I would not introduce a sparse (or other) range encoding for now for those masks, for simplicity. If we really come across a dataset which would benefit from it we can reevaluate it.
