### ISSUE TITLE
Which domain types do we need?

### ISSUE THREAD

**Issue by neothemachine** [Reading-eScience-Centre/coveragejson#6]
The CF conventions also cover domain types in chapter 9 ["Discrete Sampling Geometries"](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/build/cf-conventions.html#idp7424512). They include Point, TimeSeries (we: PointSeries), Trajectory, Profile, TrajectoryProfile (we: Section) and have in addition to ours TimeSeriesProfile (which we would call ProfileSeries). Grid is not mentioned explicitly as it is the default way of how to store data in CF. They also define how to represent data for collections of same-type coverages and introduce a ragged array representation for that where e.g. the sequences of vertical coordinates for several profiles are stacked behind each other with an additional "count" variable to separate the profiles again (they also have an alternative ragged form with an "index" variable for real-time data where the count is unknown before-hand).

It is interesting that they don't have a MultiPointSeries ("MultiTimeSeries") type. Does this indicate that such coverage is very rare?

**Comment by jonblower** [comment]
I can't think of a use case for MultiPointSeries. I don't think I've ever seen data like that.

**Comment by neothemachine** [comment]
> I can't think of a use case for MultiPointSeries. I don't think I've 
> ever seen data like that.
>
Ok, let's remove it then.

**Comment by neothemachine** [comment]
From #7: We may need a MultiPolygon domain type which is useful when you cannot use a Grid with bounds, e.g. for things like land parcels.

I wonder if profiles for Polygons make sense, as in PolygonProfile or PolygonProfileSeries. What's the use case here?

**Comment by jonblower** [comment]
I guess a PolygonProfile(Series) would occur when you have a timeseries (or profile) that has been aggregated from point data so that it is representative of a polygon. But I'm not sure we have a concrete use case yet. I'd be happy to remove them for the moment, although it may be worth considering "reserving" some names for future use so we don't end up with confusing names.

**Comment by neothemachine** [comment]
Linked to https://github.com/Reading-eScience-Centre/coveragejson/issues/24

**Comment by neothemachine** [comment]
Closing this. If any specific domain type is needed, let's open a new issue.
