### ISSUE TITLE
Rename CRS "axes" to "csAxes"

### ISSUE THREAD

**Issue by neothemachine** [Reading-eScience-Centre/coveragejson#67]
In cases when CRS details are embedded like for [vertical CRS](https://github.com/Reading-eScience-Centre/coveragejson/blob/master/spec.md#51-spatial-reference-systems) which don't have a URI, then currently the property "axes" is reused which already exists in the domain:

```js
{
  "type": "VerticalCRS",
  "id": "http://www.opengis.net/def/crs/EPSG/0/5703"
  "datum": {
    "id": "http://www.opengis.net/def/datum/EPSG/0/5103",
    "label": {
      "en": "North American Vertical Datum 1988"
    }
  },
  "cs": {
    "id": "http://www.opengis.net/def/cs/EPSG/0/6499",
    "axes": [{
      "id": "http://www.opengis.net/def/axis/EPSG/0/114",
      "name": {
        "en": "Gravity-related height"
      },
      "direction": "up",
      "unit": {
        "symbol": "m"
      }
    }]
  }
}
```

I propose to rename this to "csAxes" to disambiguate it, considering that there won't be a new JSON-LD version in the near future which would possibly allow to associate different URIs to identical property names within different locations of a document. It is an acceptable compromise I think.

**Comment by jonblower** [comment]
Sounds good
