### ISSUE TITLE
Domain type "Polygon" collides with same-named axis value data type

### ISSUE THREAD

**Issue by neothemachine** [Reading-eScience-Centre/coveragejson#68]
```js
{
  "type" : "Coverage",
  "domain" : {
    "type": "Domain",
    "domainType": "Polygon",
    "axes": {
      "composite": {
        "dataType": "Polygon",
        "components": ["x","y"],
        "values": [
          [ [ [100.0, 0.0], [101.0, 0.0], [101.0, 1.0], [100.0, 1.0], [100.0, 0.0] ]  ]
        ]
      },
...
```

The JSON-LD context includes:
```js
"domainType": { "@id": "covjson:domainType", "@type": "@vocab" },
"dataType": { "@id": "covjson:dataType", "@type": "@vocab" },
"Polygon": "covjson:Polygon",
// and later... by oversight
"Polygon": "covjsondt:Polygon" // different namespace for domain types
```
So this is not working when interpreting this with a JSON-LD client as you can't define separate sets of vocabulary terms for different properties, rather it's all global.

I see three options:
1. The values for "domainType" become full URIs. E.g. https://covjson.org/def/domainTypes#Polygon
2. The values for "domainType" get a namespace prefix, like `"common:Polygon"`. This seems weird as it would be the only place where that's done.
3. The axis value data types get lower-cased to "tuple" and "polygon". This would fit with the "dataType" field in range objects which have "float", "integer", "string" as value.

Option 1:
```js
{
  "type" : "Coverage",
  "domain" : {
    "type": "Domain",
    "domainType": "https://covjson.org/def/domainTypes#Polygon",
    "axes": {
      "composite": {
        "dataType": "Polygon",
        "components": ["x","y"],
        "values": [
          [ [ [100.0, 0.0], [101.0, 0.0], [101.0, 1.0], [100.0, 1.0], [100.0, 0.0] ]  ]
        ]
      },
...
```

Option 2:
```js
{
  "type" : "Coverage",
  "domain" : {
    "type": "Domain",
    "domainType": "common:Polygon",
    "axes": {
      "composite": {
        "dataType": "Polygon",
        "components": ["x","y"],
        "values": [
          [ [ [100.0, 0.0], [101.0, 0.0], [101.0, 1.0], [100.0, 1.0], [100.0, 0.0] ]  ]
        ]
      },
...
```

Option 3:
```js
{
  "type" : "Coverage",
  "domain" : {
    "type": "Domain",
    "domainType": "Polygon",
    "axes": {
      "composite": {
        "dataType": "polygon",
        "components": ["x","y"],
        "values": [
          [ [ [100.0, 0.0], [101.0, 0.0], [101.0, 1.0], [100.0, 1.0], [100.0, 0.0] ]  ]
        ]
      },
...
```

I prefer option 3. It's a simple convention that works. And it doesn't complicate anything.

**Comment by jonblower** [comment]
I prefer option 3 too. Although I do find that using "Polygon" as a domain type is a bit odd, because I would usually think that "Polygon" is a geometry. Calling it "PolygonDomain" would clarify this, but we might not want to call all the domain types "XDomain". Or maybe this would be better?

(In any case, the upper/lower case convention of option 3 should still be used I think.)

**Comment by neothemachine** [comment]
Let's not overcomplicate it, after all we just want to say "it's a 
domain/coverage with a XX domain type" and not "it's a domain/coverage 
with a XXDomain domain type" or similar. I'll do option 3.

**Comment by jonblower** [comment]
Fine
