### ISSUE TITLE
Bounds: independent and/or shared-neighbor model?

### ISSUE THREAD

**Issue by neothemachine** [Reading-eScience-Centre/coveragejson#9]
When you have a coordinate axis like `"x": [1,2,3]` and you want to specify bounds then for a grid it is probably always the case that neighbouring bound edges are the same, so these could be left of as it would be redundant, e.g. `"xBounds": [0.5,1.5,2.5,3.5]`. However for other typed like times, it makes more sense to be able to give for each coordinate the left and right bound separately, e.g. for `"t": ["2010-01-01","2011-05-01"]` you could have 
```js
"tBounds": [
  "2009-12-01","2010-02-01",
  "2011-01-01","2011-12-01"
]
```

In netCDF-CF only the second form is supported, so maybe we should follow that to keep it simple. The first form is more or less only about efficiency. To support that as well we could have a separate suffix like `"xBoundsAdjacent"` but I'm not sure if that's maybe too much, as every additional form complicates clients.

**Comment by neothemachine** [comment]
Another issue with bounds is when they are missing and whether the client should be allowed to derive those in some way. For grids, this makes sense mostly to derive cells, but probably only for the spatial parts and not the time. We probably have to define some defaults and then allow to influence the behaviour by indicating the bounds type somehow, like ValueIsCell and ValueIsPoint etc.

**Comment by jonblower** [comment]
ncWMS has default behaviour whereby it automatically derives bounds for x and y but not z or t (for gridded data at least). For other domain types it may not be sensible to automatically derive bounds.

(And even with model grids there can be a difference. Quantities like temperature and velocity are often strictly only simulated at the central point, but "integrated" quantities like rainfall are often considered to be summed over the cell.)

**Comment by neothemachine** [comment]
Closing this since we settled on independent bounds similar to CF. The issue of what to do when bounds are missing should be discussed in a separate issue.
